/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.TouristicPlace.view;

import ec.edu.espe.TouristicPlace.model.TouristicPlace;
import ec.edu.espe.controller.Controller;
import javax.swing.JOptionPane;
import utils.FileManager;

/**
 *
 * @author Eduardo Cambi
 */
public class FrmTouristicPlace extends javax.swing.JFrame {

    /**
     * Creates new form TuristicsPlaces
     */
    public FrmTouristicPlace() {
        initComponents();
        Controller placeController = new Controller();
        String[] lines = new String[FileManager.countLines("Touristic Place")];
        TouristicPlace [] touristicplace = new TouristicPlace[FileManager.countLines("Touristic Place")];
        
        placeController.read(lines, touristicplace);
        
        placeController.populateTouristicPlaceTable(tblPlace, touristicplace);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox<>();
        txtLatitude = new javax.swing.JTextField();
        txtLongitude = new javax.swing.JTextField();
        txtLatitudeStart = new javax.swing.JTextField();
        txtLongitudeStart = new javax.swing.JTextField();
        txtDistance = new javax.swing.JTextField();
        btnSavePLace = new javax.swing.JButton();
        btnFindPlace = new javax.swing.JButton();
        btnComputerDistance = new javax.swing.JButton();
        btnShowPlace = new javax.swing.JButton();
        txtArePlace = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlace = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Zilla Slab SemiBold", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Touristic Place");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Name of the touristic place :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Type:");

        jLabel4.setFont(new java.awt.Font("Zilla Slab SemiBold", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Ubication");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Latitude:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Longitude:");

        jLabel7.setFont(new java.awt.Font("Zilla Slab SemiBold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Starting Point");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Latitude:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Longitude:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Distance:");

        cmbType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parks", "Churches", "Places", "ViewPoint", "Malls" }));

        btnSavePLace.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnSavePLace.setForeground(new java.awt.Color(0, 51, 51));
        btnSavePLace.setText("Save");
        btnSavePLace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePLaceActionPerformed(evt);
            }
        });

        btnFindPlace.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnFindPlace.setForeground(new java.awt.Color(0, 51, 51));
        btnFindPlace.setText("Find Place");
        btnFindPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPlaceActionPerformed(evt);
            }
        });

        btnComputerDistance.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnComputerDistance.setForeground(new java.awt.Color(0, 51, 51));
        btnComputerDistance.setText("Distance");
        btnComputerDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputerDistanceActionPerformed(evt);
            }
        });

        btnShowPlace.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnShowPlace.setForeground(new java.awt.Color(0, 51, 51));
        btnShowPlace.setText("Show Place");
        btnShowPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPlaceActionPerformed(evt);
            }
        });

        tblPlace.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "type", "Latitude", "Longitude", "Latitude Start", "Longitude Start", "Distance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPlace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlaceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPlace);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLongitudeStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLatitudeStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLongitude, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLatitude, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSavePLace)
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnComputerDistance)
                                    .addComponent(btnFindPlace)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(txtArePlace))
                .addGap(173, 173, 173))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowPlace)
                .addGap(332, 332, 332))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(25, 25, 25)
                                .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtLatitudeStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLongitudeStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDistance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addGap(49, 49, 49)
                        .addComponent(txtArePlace, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShowPlace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSavePLace)
                    .addComponent(btnFindPlace))
                .addGap(31, 31, 31)
                .addComponent(btnComputerDistance)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSavePLaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePLaceActionPerformed
        TouristicPlace touristicplace;
        String name;
        String type;
        float latitude;
        float longitude;
        float distance;
        float LatitudeStar;
        float LongitudeStar;

        Controller placecontroller = new Controller();

        name = txtName.getText();
        type = cmbType.getSelectedItem().toString();
        latitude = Float.parseFloat(txtLatitude.getText());
        longitude = Float.parseFloat(txtLongitude.getText());
        distance = Float.parseFloat(txtDistance.getText());
        LatitudeStar = Float.parseFloat(txtLatitudeStart.getText());
        LongitudeStar = Float.parseFloat(txtLongitudeStart.getText());

        touristicplace = new TouristicPlace(name, type, longitude, latitude, distance, LongitudeStar, LatitudeStar);
        placecontroller.save(touristicplace);

        JOptionPane.showMessageDialog(rootPane, touristicplace.getName());

        
        
        btnShowPlaceActionPerformed(evt);

    }//GEN-LAST:event_btnSavePLaceActionPerformed

    private void btnComputerDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputerDistanceActionPerformed
       float longuitude;
       float latitude;
       float latitudeStart;
       float longitudeStart;
       float distance;
       
       
        Controller  placeController = new Controller();
        
        latitude = Float.parseFloat(txtLatitude.getText());
        longuitude = Float.parseFloat(txtLongitude.getText());
        latitudeStart = Float.parseFloat(txtLatitudeStart.getText());
        longitudeStart = Float.parseFloat(txtLongitudeStart.getText());
        distance = placeController.distanciaCoord(latitude, longuitude,latitudeStart,longitudeStart);
        txtDistance.setText(String.valueOf(distance));
        
       
    }//GEN-LAST:event_btnComputerDistanceActionPerformed

    private void btnFindPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPlaceActionPerformed
         String[] lines = new String[FileManager.countLines("touristicplace")];
        Controller placeController = new Controller();
        TouristicPlace[] touristicplace = new TouristicPlace[FileManager.countLines("touristicplace")];
        placeController.read(lines, touristicplace); 
        int index = placeController.find(touristicplace,txtName.getText());
        if (index == -1) {
            JOptionPane.showMessageDialog(rootPane, "NOT FOUND", "NOT FOUND", JOptionPane.ERROR_MESSAGE);
        } else {
            tblPlace.setRowSelectionInterval(index, index);
        }

    }//GEN-LAST:event_btnFindPlaceActionPerformed

    private void btnShowPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPlaceActionPerformed
     String[] lines = new String[FileManager.countLines("Touristic Place")];
       Controller placeController = new Controller();
       TouristicPlace[] touristicPlaces = new TouristicPlace[FileManager.countLines("Touristic Place")];

       placeController.read(lines, touristicPlaces);

       for (TouristicPlace touristicPlace : touristicPlaces) { 
           txtArePlace.setText(txtArePlace.getText() + "\n" + touristicPlace.getName());
        }
       placeController.populateTouristicPlaceTable(tblPlace, touristicPlaces);        
    }//GEN-LAST:event_btnShowPlaceActionPerformed

    private void tblPlaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlaceMouseClicked
        int column = 0;
        int row = tblPlace.getSelectedRow();
        String name = tblPlace.getModel().getValueAt(row, column).toString();
        txtName.setText(name);
        column=1;
        String type = tblPlace.getModel().getValueAt(row, column).toString();
        cmbType.setSelectedItem(type);
        column=2;
        String latitude = tblPlace.getModel().getValueAt(row, column).toString();
        txtLatitude.setText(latitude);
        column=3;
        String longitude = tblPlace.getModel().getValueAt(row, column).toString();
        txtLongitude.setText(longitude);
        column=4;
        String LatitudeStart = tblPlace.getModel().getValueAt(row, column).toString();
        txtLatitudeStart.setText(LatitudeStart);
        column=5;
        String LongitudeStart = tblPlace.getModel().getValueAt(row, column).toString();
        txtLongitudeStart.setText(LongitudeStart);
        column=6;
        String Distance = tblPlace.getModel().getValueAt(row, column).toString();
        txtDistance.setText(Distance);

    }//GEN-LAST:event_tblPlaceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTouristicPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTouristicPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTouristicPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTouristicPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTouristicPlace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComputerDistance;
    private javax.swing.JButton btnFindPlace;
    private javax.swing.JButton btnSavePLace;
    private javax.swing.JButton btnShowPlace;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPlace;
    private javax.swing.JTextField txtArePlace;
    private javax.swing.JTextField txtDistance;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLatitudeStart;
    private javax.swing.JTextField txtLongitude;
    private javax.swing.JTextField txtLongitudeStart;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
